"use client";

import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import { cancelBooking, checkAvailability, createBooking, createWorkspaceTeam, loadWorkspace, moveBooking, registerUser, saveRoom, setDelegation, setRoomActive } from "@/lib/actions";
import type { Booking, Room, Person, WorkspaceData } from "@/lib/data";
type Tab = "calendar" | "bookings" | "rooms" | "people" | "delegations" | "activity" | "teams";
type View = "month" | "week" | "day";
type Draft = { id?: string; title: string; roomId: string; date: string; start: string; end: string };
const empty: WorkspaceData = { teams: [], team: { id: "", name: "" }, rooms: [], users: [], bookings: [], delegations: [], audit: [] };
const today = () => { const d = new Date(); return d.getFullYear() + "-" + String(d.getMonth() + 1).padStart(2, "0") + "-" + String(d.getDate()).padStart(2, "0"); };
const dateKey = (d: Date) => d.getFullYear() + "-" + String(d.getMonth() + 1).padStart(2, "0") + "-" + String(d.getDate()).padStart(2, "0");
const localISO = (date: string, time: string) => new Date(date + "T" + time + ":00").toISOString();
const timeLabel = (v: string) => new Date(v).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" });
const errorText = (s: string) => /relation .* does not exist|schema cache|could not find the table/i.test(s) ? "The booking tables are not available in Supabase yet. Apply supabase/migrations/0001_init.sql to this project, then retry." : s;
const glyph = (symbol: string) => <span className="nav-glyph" aria-hidden="true">{symbol}</span>;

export default function Workspace() {
  const [data, setData] = useState<WorkspaceData>(empty);
  const [actorId, setActorId] = useState("");
  const [teamDraft, setTeamDraft] = useState(false);
  const [tab, setTab] = useState<Tab>("calendar");
  const [view, setView] = useState<View>("week");
  const [date, setDate] = useState(today());
  const [draft, setDraft] = useState<Draft | null>(null);
  const [roomDraft, setRoomDraft] = useState<Room | "new" | null>(null);
  const [userDraft, setUserDraft] = useState(false);
  const [query, setQuery] = useState("");
  const [loading, setLoading] = useState(true);
  const [loadError, setLoadError] = useState("");
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  const [saving, setSaving] = useState(false);
  const reload = useCallback(async (requestedTeamId?: string) => {
    setLoading(true);
    const r = await loadWorkspace(requestedTeamId);
    if (r.ok && r.data) {
      setData(r.data); setLoadError("");
      if (typeof window !== "undefined") window.localStorage.setItem("pitb-active-team", r.data.team.id);
      setActorId((old) => r.data!.users.some((u) => u.id === old) ? old : (r.data!.users.find((u) => u.role === "admin") || r.data!.users[0])?.id || "");
    } else setLoadError(errorText("error" in r ? r.error : "Workspace data was unavailable."));
    setLoading(false);
  }, []);
  useEffect(() => { void reload(typeof window === "undefined" ? undefined : window.localStorage.getItem("pitb-active-team") || undefined); }, [reload]);
  const actor = data.users.find((u) => u.id === actorId) || data.users[0];
  const rooms = useMemo(() => new Map(data.rooms.map((r) => [r.id, r])), [data.rooms]);
  const people = useMemo(() => new Map(data.users.map((u) => [u.id, u])), [data.users]);
  const confirmed = data.bookings.filter((b) => b.status === "confirmed");
  const mine = confirmed.filter((b) => b.booked_by_user_id === actor?.id || data.delegations.some((d) => d.is_active && d.delegator_user_id === b.booked_by_user_id && d.delegate_user_id === actor?.id));
  const editable = (b: Booking) => Boolean(actor && (b.booked_by_user_id === actor.id || actor.role === "admin" || data.delegations.some((d) => d.is_active && d.delegator_user_id === b.booked_by_user_id && d.delegate_user_id === actor.id)));
  const run = async (fn: () => Promise<{ok:boolean; error?:string}>, done: string) => {
    setError(""); setMessage(""); setSaving(true); const r = await fn(); setSaving(false);
    if (!r.ok) { setError(errorText(r.error || "The change could not be saved.")); return false; }
    await reload(); setMessage(done); return true;
  };
  const openNew = (day = date, at = "10:00", roomId = "") => {
    const [h, m] = at.split(":").map(Number), end = h * 60 + m + 30;
    setDraft({ title: "", roomId, date: day, start: at, end: String(Math.floor(end / 60)).padStart(2, "0") + ":" + String(end % 60).padStart(2, "0") });
  };
  const openEdit = (b: Booking) => {
    if (!editable(b)) { setMessage("Only the owner, an admin, or a delegated teammate can edit this booking."); return; }
    const s = new Date(b.start_time), e = new Date(b.end_time);
    setDraft({ id: b.id, title: b.title, roomId: b.room_id, date: dateKey(s), start: String(s.getHours()).padStart(2, "0") + ":" + String(s.getMinutes()).padStart(2, "0"), end: String(e.getHours()).padStart(2, "0") + ":" + String(e.getMinutes()).padStart(2, "0") });
  };
  const nav: [Tab, string, string][] = [["calendar","Calendar","▦"],["bookings","My bookings","☷"],["rooms","Rooms","⌂"],["people","People","♙"],["delegations","Delegations","⇄"],["activity","Activity log","◷"],["teams","Teams","◫"]];
  const focused = new Date(date + "T12:00:00");
  const shift = (step: number) => { const d = new Date(focused); d.setDate(d.getDate() + step * (view === "month" ? 1 : view === "week" ? 7 : 1)); setDate(dateKey(d)); };
  const monday = new Date(focused); monday.setDate(monday.getDate() - ((monday.getDay() + 6) % 7));
  const weekDates = Array.from({ length: 7 }, (_, i) => { const d = new Date(monday); d.setDate(d.getDate() + i); return dateKey(d); });
  const headerDate = view === "month" ? focused.toLocaleDateString([], { month: "long", year: "numeric" }) : view === "day" ? focused.toLocaleDateString([], { weekday: "long", month: "long", day: "numeric", year: "numeric" }) : new Date(weekDates[0] + "T12:00:00").toLocaleDateString([], { month: "short", day: "numeric" }) + " – " + new Date(weekDates[6] + "T12:00:00").toLocaleDateString([], { month: "short", day: "numeric", year: "numeric" });
  const bookingsOn = (d: string) => confirmed.filter((b) => dateKey(new Date(b.start_time)) === d).sort((a,b) => a.start_time.localeCompare(b.start_time));
  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><span className="brand-mark">▦</span><strong>room<span>book</span></strong><small>WORKSPACE</small></div>
      <label className="workspace-chip"><b>{data.team.name.slice(0,1) || "T"}</b><span><small>TEAM WORKSPACE</small><select aria-label="Team workspace" value={data.team.id} onChange={e => { setActorId(""); void reload(e.target.value); }}>{data.teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></span><i>⌄</i></label>
      <div className="side-caption">WORKSPACE</div><nav>{nav.map(([id,label,symbol]) => <button key={id} className={tab === id ? "nav-item nav-active" : "nav-item"} onClick={() => { setTab(id); setError(""); setMessage(""); }}>{glyph(symbol)}<span>{label}</span>{id === "bookings" && mine.length > 0 && <small className="nav-count">{mine.length}</small>}</button>)}</nav>
      <div className="side-bottom"><div className="help-row"><b>?</b><span>Need a hand?<small>Contact your IT admin</small></span></div><div className="profile"><span className="avatar">{actor?.full_name.split(" ").map(x => x[0]).slice(0,2).join("").toUpperCase() || "?"}</span><span>{actor?.full_name || "No staff registered"}<small>{actor?.role === "admin" ? "Team administrator" : "Team member"}</small></span></div></div>
    </aside>
    <main className="main"><header className="topbar"><div className="crumb">Workspace <span>/</span> <strong>{nav.find(x => x[0] === tab)?.[1]}</strong></div><label className="actor-picker">Using <select aria-label="Act as user" value={actor?.id || ""} onChange={e => setActorId(e.target.value)}>{data.users.map(u => <option value={u.id} key={u.id}>{u.full_name}{u.role === "admin" ? " · Admin" : ""}</option>)}</select></label></header>
      <div className="content">
        {loadError && <div className="error-banner"><div><b>Can’t connect to booking data</b><span>{loadError}</span></div><button className="btn secondary small" onClick={() => void reload()}>Retry</button></div>}
        {(error || message) && <div className={error ? "alert alert-error" : "alert alert-ok"} role="status">{error || message}<button onClick={() => {setError("");setMessage("");}}>×</button></div>}
        {loading && !loadError ? <div className="loading"><span className="spinner"/>Loading workspace…</div> : <>
          {tab === "calendar" && <><div className="page-head"><div><small className="eyebrow">ROOM SCHEDULING</small><h1>Your calendar</h1><p>Find a time that works. Reserve the room you need.</p></div><button className="btn primary" onClick={() => openNew()}>＋ &nbsp;Book a room</button></div>
            <div className="calendar-toolbar"><div className="date-tools"><button className="icon-btn" onClick={() => shift(-1)}>‹</button><button className="icon-btn" onClick={() => shift(1)}>›</button><button className="btn secondary today-btn" onClick={() => setDate(today())}>Today</button><h2>{headerDate}</h2></div><div className="view-toggle">{(["month","week","day"] as View[]).map(v => <button className={view === v ? "selected" : ""} key={v} onClick={() => setView(v)}>{v[0].toUpperCase()+v.slice(1)}</button>)}</div></div>
            <div className="calendar-card">
              {view === "month" && <MonthCalendar date={focused} events={bookingsOn} onDay={d => {setDate(d);openNew(d);}} onEvent={openEdit}/>}
              {view === "week" && <WeekCalendar dates={weekDates} events={bookingsOn} rooms={rooms} onSlot={(d,t) => openNew(d,t)} onEvent={openEdit}/>}
              {view === "day" && <DayCalendar date={date} rooms={data.rooms.filter(r => r.is_active)} events={bookingsOn(date)} onSlot={(t,r) => openNew(date,t,r)} onEvent={openEdit}/>}
              {!data.rooms.some(r => r.is_active) && <p className="calendar-hint">No rooms yet. <button onClick={() => setTab("rooms")}>Add a room</button> to start booking.</p>}
            </div><div className="calendar-caption"><span><i/> Confirmed booking</span><span>Times shown in your local timezone</span></div>
          </>}
          {tab === "bookings" && <><PageHeader eyebrow="YOUR SCHEDULE" title="My bookings" desc="Your meetings and the bookings shared with you." action={<button className="btn primary" onClick={() => {setTab("calendar");openNew();}}>＋ &nbsp;Book a room</button>}/><div className="list-top"><span>{mine.length} bookings</span><Search value={query} setValue={setQuery} placeholder="Search bookings"/></div><BookingList rows={mine.filter(b => b.title.toLowerCase().includes(query.toLowerCase()))} rooms={rooms} people={people} editable={editable} onEdit={openEdit} onCancel={b => actor && confirm("Cancel “" + b.title + "”?") && void run(() => cancelBooking(data.team.id,b.id,actor.id),"Booking cancelled.")}/></>}
          {tab === "rooms" && <><PageHeader eyebrow="SPACE DIRECTORY" title="Rooms" desc="Meeting spaces available to your team." action={actor?.role === "admin" ? <button className="btn primary" onClick={() => setRoomDraft("new")}>＋ &nbsp;Add a room</button> : null}/><div className="room-stats"><b>{data.rooms.filter(r => r.is_active).length}</b> active spaces <i/> <b>{data.rooms.filter(r => r.is_active).reduce((n,r) => n+r.capacity,0)}</b> total seats</div><div className="room-grid">{data.rooms.map(r => <RoomCard key={r.id} room={r} isAdmin={actor?.role === "admin"} onBook={() => {setTab("calendar");openNew(date,"10:00",r.id);}} onEdit={() => setRoomDraft(r)} onToggle={() => actor && void run(() => setRoomActive(data.team.id,actor.id,r.id,!r.is_active),r.is_active ? "Room deactivated." : "Room reactivated.")}/>)}</div>{!data.rooms.length && <Empty title="Your room directory is empty" desc="Add a room so your team can get started." action={actor?.role === "admin" ? <button className="btn primary" onClick={() => setRoomDraft("new")}>Add your first room</button> : null}/>}</>}
          {tab === "people" && <><PageHeader eyebrow="TEAM DIRECTORY" title="People" desc="Staff who can book and manage shared rooms." action={actor?.role === "admin" ? <button className="btn primary" onClick={() => setUserDraft(true)}>＋ &nbsp;Register a person</button> : null}/><div className="list-top"><span>{data.users.length} team members</span><Search value={query} setValue={setQuery} placeholder="Search people"/></div><div className="people-table"><div className="table-head"><span>NAME</span><span>EMAIL</span><span>ROLE</span><span>BOOKINGS</span></div>{data.users.filter(u => (u.full_name+" "+u.email).toLowerCase().includes(query.toLowerCase())).map(u => <div className="person-row" key={u.id}><span><b className="avatar">{u.full_name.split(" ").map(x=>x[0]).slice(0,2).join("").toUpperCase()}</b><strong>{u.full_name}{u.id === actor?.id && <em>YOU</em>}</strong></span><span>{u.email}</span><span><i className={"role-pill "+u.role}>{u.role === "admin" ? "Admin" : "Staff"}</i></span><span>{confirmed.filter(b=>b.booked_by_user_id === u.id).length}</span></div>)}</div>{!data.users.length && <Empty title="No people registered" desc="Register your team before they start booking rooms."/>}</>}
          {tab === "delegations" && <DelegationPanel actor={actor} users={data.users} delegations={data.delegations} onSet={(id,active) => actor && void run(() => setDelegation({teamId:data.team.id,actorId:actor.id,delegateId:id,active}),active ? "Booking access granted." : "Delegation removed.")}/>}
          {tab === "activity" && <><PageHeader eyebrow="CHANGE HISTORY" title="Activity log" desc="A record of booking and delegation changes."/><Activity rows={data.audit} people={people} rooms={rooms}/></>}
          {tab === "teams" && <><PageHeader eyebrow="WORKSPACE SETTINGS" title="Your teams" desc="Each team has its own room directory, members, bookings, and activity." action={actor?.role === "admin" ? <button className="btn primary" onClick={() => setTeamDraft(true)}>＋ &nbsp;Create team</button> : null}/><div className="team-grid">{data.teams.map(t=><button className={t.id===data.team.id?"team-card current":"team-card"} key={t.id} onClick={()=>void reload(t.id)}><span className="team-mark">{t.name.slice(0,1).toUpperCase()}</span><span><strong>{t.name}</strong><small>{t.id===data.team.id?"Current workspace":"Switch workspace"}</small></span><b>{t.id===data.team.id?"✓":"→"}</b></button>)}</div><div className="team-footnote">Workspace data is separated by team. Add teammates from the People section after creating a team.</div></>}
        </>}
      </div>
    </main>
    {draft && actor && <BookingModal draft={draft} teamId={data.team.id} rooms={data.rooms} actor={actor} onClose={() => setDraft(null)} onSave={async values => {const result = draft.id ? await moveBooking({teamId:data.team.id,bookingId:draft.id,actorId:actor.id,...values}) : await createBooking({teamId:data.team.id,actorId:actor.id,...values}); if (!result.ok) return errorText(result.error); await reload(); setMessage(draft.id ? "Booking updated." : "Room booked successfully."); return "";}}/>}
    {roomDraft && actor && <RoomForm room={roomDraft === "new" ? undefined : roomDraft} onClose={() => setRoomDraft(null)} onSave={async values => {const result = await saveRoom({...values,teamId:data.team.id,actorId:actor.id,...(roomDraft !== "new" ? {id:roomDraft.id} : {})}); if (!result.ok) return errorText(result.error); await reload(); setRoomDraft(null); setMessage(roomDraft === "new" ? "Room added." : "Room details saved."); return "";}}/>}
    {userDraft && actor && <UserForm onClose={() => setUserDraft(false)} onSave={async values => {const result = await registerUser({...values,teamId:data.team.id,actorId:actor.id}); if (!result.ok) return errorText(result.error); await reload(); setUserDraft(false); setMessage("Person added to team."); return "";}}/>}
    {teamDraft && actor && <TeamForm onClose={()=>setTeamDraft(false)} onSave={async name=>{const result=await createWorkspaceTeam({actorId:actor.id,name});if(!result.ok)return errorText(result.error);setTeamDraft(false);setTab("teams");await reload(result.data?.id);setMessage("Team workspace created.");return "";}}/>}
    {saving && <div className="saving"><span className="spinner"/>Saving change…</div>}
  </div>;
}
function PageHeader({eyebrow,title,desc,action}:{eyebrow:string;title:string;desc:string;action?:React.ReactNode}) { return <div className="page-head"><div><small className="eyebrow">{eyebrow}</small><h1>{title}</h1><p>{desc}</p></div>{action}</div>; }
function Search({value,setValue,placeholder}:{value:string;setValue:(s:string)=>void;placeholder:string}) { return <label className="search"><span>⌕</span><input value={value} onChange={e=>setValue(e.target.value)} placeholder={placeholder}/></label>; }
function Empty({title,desc,action}:{title:string;desc:string;action?:React.ReactNode}) { return <div className="empty"><span>▦</span><h3>{title}</h3><p>{desc}</p>{action}</div>; }
function MonthCalendar({date,events,onDay,onEvent}:{date:Date;events:(s:string)=>Booking[];onDay:(s:string)=>void;onEvent:(b:Booking)=>void}) {
  const first=new Date(date.getFullYear(),date.getMonth(),1),start=new Date(first);start.setDate(1-((first.getDay()+6)%7));const cells=Array.from({length:42},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);return d;});
  return <div className="month"><div className="month-head">{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map(x=><span key={x}>{x}</span>)}</div><div className="month-body">{cells.map((d,i)=>{const key=dateKey(d),items=events(key);return <div key={i} onClick={()=>onDay(key)} className={"month-cell "+(d.getMonth()!==date.getMonth()?"outside ":"")+(key===today()?"today":"")}><b>{d.getDate()}</b>{items.slice(0,2).map(b=><button key={b.id} className="month-event" onClick={e=>{e.stopPropagation();onEvent(b);}}><i/>{b.title}</button>)}{items.length>2&&<small>+{items.length-2} more</small>}</div>;})}</div></div>;
}
function WeekCalendar({dates,events,rooms,onSlot,onEvent}:{dates:string[];events:(s:string)=>Booking[];rooms:Map<string,Room>;onSlot:(d:string,t:string)=>void;onEvent:(b:Booking)=>void}) {
  const slots=Array.from({length:20},(_,i)=>({h:8+Math.floor(i/2),m:i%2?30:0}));
  return <div className="grid-scroll"><div className="week"><div className="time-head">GMT+8</div>{dates.map(d=><div className={"weekday "+(d===today()?"today":"")} key={d}><small>{new Date(d+"T12:00:00").toLocaleDateString([],{weekday:"short"})}</small><b>{new Date(d+"T12:00:00").getDate()}</b></div>)}{slots.map(s=><div className="week-row" key={s.h+":"+s.m}><div className="time-label">{s.m===0?String(s.h).padStart(2,"0")+":00":""}</div>{dates.map(d=>{const items=events(d).filter(b=>{const x=new Date(b.start_time);return x.getHours()===s.h&&Math.floor(x.getMinutes()/30)===(s.m?1:0);});return <div key={d+s.h+s.m} className="week-slot" onClick={()=>onSlot(d,String(s.h).padStart(2,"0")+":"+String(s.m).padStart(2,"0"))}>{items.map(b=><button key={b.id} className="week-event" onClick={e=>{e.stopPropagation();onEvent(b);}}><b>{b.title}</b><small>{rooms.get(b.room_id)?.name||"Room"}</small></button>)}</div>;})}</div>)}</div></div>;
}
function DayCalendar({date,rooms,events,onSlot,onEvent}:{date:string;rooms:Room[];events:Booking[];onSlot:(t:string,r:string)=>void;onEvent:(b:Booking)=>void}) {
  const slots=Array.from({length:20},(_,i)=>({h:8+Math.floor(i/2),m:i%2?30:0}));
  return <div className="grid-scroll"><div className="day-grid" style={{gridTemplateColumns:"65px repeat("+rooms.length+", minmax(150px, 1fr))"}}><div className="time-head">{new Date(date+"T12:00:00").toLocaleDateString([],{weekday:"short",month:"short",day:"numeric"})}</div>{rooms.map(r=><div className="day-room" key={r.id}>{r.name}<small>{r.capacity} seats</small></div>)}{slots.map(s=><div className="day-row" key={s.h+":"+s.m}><div className="time-label">{s.m===0?String(s.h).padStart(2,"0")+":00":""}</div>{rooms.map(r=>{const items=events.filter(b=>b.room_id===r.id&&new Date(b.start_time).getHours()===s.h&&Math.floor(new Date(b.start_time).getMinutes()/30)===(s.m?1:0));return <div className="day-slot" key={r.id+s.h+s.m} onClick={()=>onSlot(String(s.h).padStart(2,"0")+":"+String(s.m).padStart(2,"0"),r.id)}>{items.map(b=><button className="day-event" key={b.id} onClick={e=>{e.stopPropagation();onEvent(b);}}><b>{b.title}</b><small>{timeLabel(b.start_time)} – {timeLabel(b.end_time)}</small></button>)}</div>;})}</div>)}</div></div>;
}
function BookingModal({draft,teamId,rooms,actor,onClose,onSave}:{draft:Draft;teamId:string;rooms:Room[];actor:Person;onClose:()=>void;onSave:(values:{roomId:string;title:string;start:string;end:string})=>Promise<string>}) {
  const [title,setTitle]=useState(draft.title),[roomId,setRoomId]=useState(draft.roomId||rooms.find(r=>r.is_active)?.id||""),[start,setStart]=useState(draft.start),[end,setEnd]=useState(draft.end),[available,setAvailable]=useState<boolean|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
  useEffect(()=>{if(!roomId||!start||!end||end<=start){setAvailable(null);return;}let alive=true;checkAvailability(teamId,roomId,localISO(draft.date,start),localISO(draft.date,end),draft.id).then(r=>alive&&setAvailable(r.ok?r.data??null:null));return()=>{alive=false;};},[teamId,roomId,start,end,draft.date,draft.id]);
  const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError("");const message=await onSave({roomId,title,start:localISO(draft.date,start),end:localISO(draft.date,end)});setBusy(false);if(message){setError(message);return;}onClose();};
  return <Modal title={draft.id?"Update your meeting":"Reserve a room"} eyebrow={draft.id?"EDIT BOOKING":"NEW BOOKING"} onClose={onClose}><form className="form" onSubmit={submit}><label>Meeting title<input autoFocus required maxLength={100} placeholder="e.g. Team Sync" value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Room<select required value={roomId} onChange={e=>setRoomId(e.target.value)}><option value="">Select a room</option>{rooms.filter(r=>r.is_active).map(r=><option value={r.id} key={r.id}>{r.name} · {r.location||"Location not set"} · {r.capacity} seats</option>)}</select></label><div className="two-fields"><label>Date<input type="date" value={draft.date} readOnly/></label><label>Attending as<input value={actor.full_name} readOnly/></label></div><div className="two-fields"><label>Start time<input type="time" step={1800} required value={start} onChange={e=>setStart(e.target.value)}/></label><label>End time<input type="time" step={1800} required value={end} onChange={e=>setEnd(e.target.value)}/></label></div><div className={"availability "+(available===true?"free":available===false?"busy":"")}>{available===true?"✓ Room is available":available===false?"! Already booked at that time":"Choose a room and time to check availability"}</div>{error&&<div className="form-error">{error}</div>}<div className="modal-actions"><button type="button" className="btn secondary" onClick={onClose}>Cancel</button><button className="btn primary" disabled={busy||!rooms.some(r=>r.is_active)}>{busy?"Saving…":draft.id?"Save changes":"Create booking"}</button></div></form></Modal>;
}
function BookingList({rows,rooms,people,editable,onEdit,onCancel}:{rows:Booking[];rooms:Map<string,Room>;people:Map<string,Person>;editable:(b:Booking)=>boolean;onEdit:(b:Booking)=>void;onCancel:(b:Booking)=>void}) {
  if(!rows.length)return <Empty title="No bookings yet" desc="When you reserve a room or receive a delegation, it will show up here."/>;return <div className="booking-list">{[...rows].sort((a,b)=>a.start_time.localeCompare(b.start_time)).map(b=><article className="booking-row" key={b.id}><div className="date-badge"><b>{new Date(b.start_time).getDate()}</b><small>{new Date(b.start_time).toLocaleDateString([],{month:"short"}).toUpperCase()}</small></div><div className="booking-info"><h3>{b.title}{!editable(b)&&<em>Shared with you</em>}</h3><p>{timeLabel(b.start_time)} – {timeLabel(b.end_time)} <span>·</span> {rooms.get(b.room_id)?.name||"Room"} <span>·</span> {people.get(b.booked_by_user_id||"")?.full_name||"Staff"}</p></div><div className="row-actions">{editable(b)&&<button className="btn secondary small" onClick={()=>onEdit(b)}>Edit</button>}{editable(b)&&<button className="icon-btn" onClick={()=>onCancel(b)} aria-label="Cancel booking">×</button>}</div></article>)}</div>;
}
function RoomCard({room,isAdmin,onBook,onEdit,onToggle}:{room:Room;isAdmin:boolean;onBook:()=>void;onEdit:()=>void;onToggle:()=>void}) {
  return <article className={"room-card "+(!room.is_active?"inactive":"")}><div className="room-art"><div className="room-sun"/><div className="room-table"/><div className="room-chair one"/><div className="room-chair two"/><b>{String(room.capacity).padStart(2,"0")}<small>SEATS</small></b><span>SEL / PROPERTIES</span></div><div className="room-body"><div className="room-name"><div><h3>{room.name}</h3><small>⌖ &nbsp;{room.location||"Location not set"}</small></div><i className={room.is_active?"active":"inactive"}>{room.is_active?"Available":"Inactive"}</i></div><p>♧ &nbsp;Up to <b>{room.capacity} people</b></p><div className="amenities">{room.amenities?.length?room.amenities.map(a=><span key={a}>{a.replaceAll("-"," ")}</span>):<span>No amenities listed</span>}</div><div className="room-actions">{room.is_active&&<button className="btn primary" onClick={onBook}>Book room</button>}{isAdmin&&<button className="btn secondary" onClick={onEdit}>Edit</button>}{isAdmin&&<button className="link-action" onClick={onToggle}>{room.is_active?"Deactivate":"Reactivate"}</button>}</div></div></article>;
}
function DelegationPanel({actor,users,delegations,onSet}:{actor?:Person;users:Person[];delegations:WorkspaceData["delegations"];onSet:(id:string,active:boolean)=>void}) {
  const [pick,setPick]=useState("");const active=delegations.filter(d=>d.delegator_user_id===actor?.id&&d.is_active);
  return <><PageHeader eyebrow="SHARED ACCESS" title="Delegations" desc="Let a trusted teammate manage bookings on your behalf."/><div className="delegate-note"><b>⇄</b><div><strong>Booking access, on your terms</strong><p>Your delegate can update or cancel your room bookings. You stay the owner, and every change is recorded.</p></div></div><section className="panel"><div className="panel-heading"><div><h2>People with access</h2><p>Manage who can edit your bookings.</p></div><span>{active.length} active</span></div><div className="delegate-add"><select value={pick} onChange={e=>setPick(e.target.value)}><option value="">Choose a teammate to delegate to</option>{users.filter(u=>u.id!==actor?.id&&!active.some(d=>d.delegate_user_id===u.id)).map(u=><option value={u.id} key={u.id}>{u.full_name} · {u.email}</option>)}</select><button className="btn primary" disabled={!pick} onClick={()=>{onSet(pick,true);setPick("");}}>＋ &nbsp;Grant access</button></div>{active.length?active.map(d=>{const u=users.find(x=>x.id===d.delegate_user_id);return <div className="delegate-row" key={d.id}><b className="avatar">{u?.full_name.split(" ").map(x=>x[0]).slice(0,2).join("").toUpperCase()}</b><span><strong>{u?.full_name||"Teammate"}</strong><small>{u?.email}</small></span><i>✓ Can edit bookings</i><button className="btn secondary small" onClick={()=>onSet(d.delegate_user_id,false)}>Revoke</button></div>;}):<div className="delegate-empty">You haven’t shared booking access with anyone yet.</div>}</section><section className="shared-note"><h2>Bookings shared with you</h2><p>Use the person menu in the top bar to switch to the teammate who delegated access.</p></section></>;
}
function Activity({rows,people,rooms}:{rows:WorkspaceData["audit"];people:Map<string,Person>;rooms:Map<string,Room>}) {
  if(!rows.length)return <Empty title="No activity recorded" desc="Booking changes and delegation updates will appear here."/>;const labels:Record<string,string>={create:"created a booking",update:"updated a booking",cancel:"cancelled a booking",delegation_granted:"granted booking access",delegation_revoked:"revoked booking access"};
  return <div className="activity-list">{rows.map(row=>{const changes=row.changes||{},after=changes.after as Record<string,unknown>|undefined,title=String(changes.title||after?.title||"Booking"),room=String(changes.room_id||after?.room_id||"");return <article key={row.id}><b className="activity-symbol">{row.action==="create"?"+":row.action.includes("delegation")?"⇄":"↻"}</b><div><p><strong>{people.get(row.actor_user_id||"")?.full_name||"A team member"}</strong> {labels[row.action]||"changed a booking"} {row.action.includes("delegation")?"":<strong>{title}</strong>}</p><small>{rooms.get(room)?.name||"Room"} · {new Date(row.created_at).toLocaleString([],{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})}</small></div><span>{row.action.replaceAll("_"," ")}</span></article>;})}</div>;
}
function Modal({title,eyebrow,onClose,children}:{title:string;eyebrow:string;onClose:()=>void;children:React.ReactNode}) { return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="modal"><header><div><small className="eyebrow">{eyebrow}</small><h2>{title}</h2></div><button className="icon-btn" onClick={onClose}>×</button></header>{children}</section></div>; }
function RoomForm({room,onClose,onSave}:{room?:Room;onClose:()=>void;onSave:(v:{name:string;location:string;capacity:number;amenities:string[]})=>Promise<string>}) {
  const [name,setName]=useState(room?.name||""),[location,setLocation]=useState(room?.location||""),[capacity,setCapacity]=useState(String(room?.capacity||4)),[amenity,setAmenity]=useState(room?.amenities.join(", ")||""),[error,setError]=useState("");
  return <Modal title={room?"Edit room":"Add a room"} eyebrow="ROOM DETAILS" onClose={onClose}><form className="form" onSubmit={async e=>{e.preventDefault();const err=await onSave({name,location,capacity:Number(capacity),amenities:amenity.split(",").map(x=>x.trim()).filter(Boolean)});setError(err);}}><label>Room name<input required value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Huddle B"/></label><label>Location<input value={location} onChange={e=>setLocation(e.target.value)} placeholder="e.g. Floor 2"/></label><div className="two-fields"><label>Capacity<input required type="number" min="1" value={capacity} onChange={e=>setCapacity(e.target.value)}/></label><label>Amenities<input value={amenity} onChange={e=>setAmenity(e.target.value)} placeholder="Projector, whiteboard"/></label></div>{error&&<div className="form-error">{error}</div>}<div className="modal-actions"><button type="button" className="btn secondary" onClick={onClose}>Cancel</button><button className="btn primary">{room?"Save room":"Add room"}</button></div></form></Modal>;
}
function UserForm({onClose,onSave}:{onClose:()=>void;onSave:(v:{fullName:string;email:string;role:"staff"|"admin"})=>Promise<string>}) {
  const [fullName,setName]=useState(""),[email,setEmail]=useState(""),[role,setRole]=useState<"staff"|"admin">("staff"),[error,setError]=useState("");
  return <Modal title="Register a person" eyebrow="TEAM DIRECTORY" onClose={onClose}><form className="form" onSubmit={async e=>{e.preventDefault();const err=await onSave({fullName,email,role});setError(err);}}><label>Full name<input required value={fullName} onChange={e=>setName(e.target.value)} placeholder="e.g. Jane Tan"/></label><label>Company email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="jane@company.com"/></label><label>Role<select value={role} onChange={e=>setRole(e.target.value as "staff"|"admin")}><option value="staff">Staff member</option><option value="admin">IT administrator</option></select></label><p className="form-hint">Registering someone gives them access to this demo booking workspace.</p>{error&&<div className="form-error">{error}</div>}<div className="modal-actions"><button type="button" className="btn secondary" onClick={onClose}>Cancel</button><button className="btn primary">Register person</button></div></form></Modal>;
}
function TeamForm({onClose,onSave}:{onClose:()=>void;onSave:(name:string)=>Promise<string>}) {
  const [name,setName]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);
  return <Modal title="Create a team workspace" eyebrow="NEW WORKSPACE" onClose={onClose}><form className="form" onSubmit={async e=>{e.preventDefault();setBusy(true);const message=await onSave(name);setBusy(false);setError(message);}}><label>Team name<input required autoFocus maxLength={80} value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Product & Design"/></label><p className="form-hint">Your current profile will be the first team administrator. Rooms, members, bookings and activity start separately for this workspace.</p>{error&&<div className="form-error">{error}</div>}<div className="modal-actions"><button type="button" className="btn secondary" onClick={onClose}>Cancel</button><button className="btn primary" disabled={busy}>{busy?"Creating…":"Create workspace"}</button></div></form></Modal>;
}
